[tools]
bun = "latest"
delta = "latest"
go = "1.24"
node = "lts"
"npm:prettier" = "latest"
python = ["3.12", "3.13"]
ruby = ["3.2", "3.3", "3.4"]
terraform = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "python", "terraform"]

[settings.npm]
bun = true
